/**
 * Broadcast chatter (2-4 sentences: color commentary, banter, filler, anecdotes about the situation) and a block of general sentences for
 * phonetic coverage. Written for this project; nothing here quotes a real broadcaster. Slots as in templates.ts.
 */
import type { Style } from './types';

export interface Free {
  style: Style;
  text: string;
}

const c = (style: Style, text: string): Free => ({ style, text });

/** Chatter, in rough order of priority: the first ones are used in the pilot, then core, then extended. */
export const CHATTER: Free[] = [
  c('deadpan', "You know, the thing about a night game is the ball just carries differently. The air gets heavy after the sun goes down, and the pitchers like it. I do not think the hitters would agree."),
  c('deadpan', 'Look at {name} out there, never in a hurry. Takes his time, adjusts the glove, looks the runner back. That kind of patience wins you games in September.'),
  c('calm', 'A lovely evening here at Claudeball. Not a cloud in the sky, a light breeze coming in from left, and a crowd that has been on its feet since the first pitch.'),
  c('deadpan', 'If you have ever wondered why the catcher is so tired by the seventh, count the pitches. Every one of those is a squat, a throw, a signal, a block. It adds up.'),
  c('building', 'This is where it gets interesting. Tie game, late innings, the bullpen is warming up, and everybody in this ballpark knows what one swing can do.'),
  c('deadpan', 'There is an old saying that good pitching beats good hitting. Tonight it is more like good pitching beats good hitting, and good defense beats everybody.'),
  c('calm', 'The {team} have been a different club since the break. The pitching is deeper, the bats have woken up, and the bench keeps coming through.'),
  c('deadpan', 'You can learn a lot about a hitter from how he handles two strikes. {name} shortens up, spreads out a little, and just tries to put the ball in play.'),
  c('deadpan', 'Funny thing about the changeup. When it works, nobody remembers it, and when it hangs, nobody forgets it.'),
  c('building', 'Seventh inning, one run game, runner on second. If this does not get you out of your seat, you might want to check your pulse.'),
  c('deadpan', 'The shortstop is playing deep, almost on the grass behind second. That is a sign they respect the pull side, and they do not want a ball through the hole.'),
  c('calm', 'There is something about a ballpark at dusk. The lights come on, the grass glows, and for a few hours nothing else in the world matters.'),
  c('deadpan', 'Every pitcher has a pitch he trusts when it gets tight. For {name} it is the slider, down and away, and he has not shied away from it all night.'),
  c('deadpan', 'Watch the first baseman hold the runner. A little extra lead here and the pitcher has to think about the pickoff, and that is half the battle.'),
  c('calm', 'The crowd is settling in now. A few more people are making their way to their seats with a hot dog in each hand, which is how you know it is a good game.'),
  c('deadpan', 'People ask me what the hardest thing in sports is. Hitting a round ball with a round bat, coming at you at ninety-five, in about four tenths of a second. Pretty sure that is the answer.'),
  c('building', 'Two on, two out, and the best hitter in this lineup is coming up. Somebody is going to have to make a pitch here.'),
  c('deadpan', 'A good bunt is one of the prettiest plays in this game, and almost nobody notices it. You give up an out, you move a runner, and the manager nods in the dugout.'),
  c('deadpan', 'Outfielders are like goalies. You only really notice them when something goes wrong, or when they do something that should not be humanly possible.'),
  c('calm', 'The infield is cut, the lines are fresh, the mound is perfect. Somebody put a lot of work into this field today, and I hope the players appreciate it.'),
  c('deadpan', 'The strike zone is a living thing. It breathes a little bit from inning to inning, and the best hitters figure out where the umpire is giving them the corner.'),
  c('deadpan', 'Teams used to pitch backward to the leadoff man every single time. Now they just attack him with strikes, because walking him is worse than anything he can do.'),
  c('building', 'You can feel it in the ballpark. The noise is building, the pitcher is working fast, and the hitters are getting a little antsy.'),
  c('deadpan', 'The thing about a double switch is that nobody notices it unless it works. And when it works, the manager looks like a genius.'),
  c('calm', 'I have been around this game a long time, and I still get a little chill when the starting lineups come out. Same ritual, same smell, same green grass.'),
  c('deadpan', 'It is a game of failure, baseball. The best hitters make out seven times in ten, and we put them in the hall of fame for it.'),
  c('deadpan', 'Catchers do not get enough credit. Calling the game, framing the borderline pitch, keeping the pitcher calm, and then blocking a curveball in the dirt with their body.'),
  c('calm', 'A quick reminder if you are just joining us. It is a tight one here at Claudeball, and the pitchers have been in charge most of the night.'),
  c('deadpan', 'There is a reason managers love a groundball pitcher with runners on. Double play is the best friend a tired bullpen ever had.'),
  c('building', 'The {team} need a spark, and {name} might be just the guy to give it to them. One good swing and this whole inning turns around.'),
  c('deadpan', 'The best base runners are not always the fastest. They read the pitcher, they read the catcher, and they get a great jump when it matters.'),
  c('deadpan', 'Do not let the box score fool you. {name} has hit three balls on the screws tonight, and has nothing to show for it.'),
  c('calm', 'Rain is a long way off, the wind is quiet, and the crowd is happy. Honestly, you could not ask for a better night for baseball.'),
  c('deadpan', 'Pitchers love to talk about a good fastball up in the zone. The hitters love to talk about it too, usually while they walk back to the dugout.'),
  c('deadpan', 'A walk is as good as a single, they say, except when it leads off an inning, and then it is better than a single.'),
  c('deadpan', 'Somewhere in the stands right now a kid is catching his first foul ball, and he will remember it for the rest of his life.'),
  c('building', 'Everything is in slow motion at a moment like this. Pitcher steps off, wipes his brow, checks the runner, and the whole park holds its breath.'),
  c('deadpan', 'The second baseman has been shading toward the bag all night. Count the pull hitters in this lineup, and you can understand why.'),
  c('calm', 'A lot of baseball is waiting. Waiting for the pitch, waiting for the ball to come down, waiting for the umpire. And then everything happens at once.'),
  c('deadpan', 'Ask any pitcher and he will tell you the same thing. The inning after you score is the most important inning of the game.'),
  c('deadpan', 'The seventh-inning stretch has been a tradition for a very long time, and I hope it never goes away. Everybody gets up, everybody sings, and then it is back to work.'),
  c('building', 'It is all coming down to this at-bat, and we are not exaggerating. Count is full, the runners are going, and the crowd has not sat down in five minutes.'),
  c('deadpan', 'You can tell a lot about the pitcher by watching the first inning. How fast he works, how he finishes the pitch, and whether his glove side stays closed.'),
  c('deadpan', 'There is an art to getting a break on a fly ball. You do not run to where it is, you run to where it will be, and you trust the math your legs already know.'),
  c('calm', 'The visitors have been hitting the ball hard all night, right at somebody. That is baseball, I suppose. Sometimes the hard hit ball is an out, and sometimes the dribbler wins you the game.'),
  c('deadpan', 'There is a stretch of the season where every team looks the same. It is the part where the schedule is a grind, and the best clubs just keep winning anyway.'),
  c('deadpan', 'Leave it to the pitcher to hit a double. They do not practice it much, but when it happens the whole dugout comes unglued.'),
  c('building', 'Down to the last out, and everything is riding on this one. {name} is a patient hitter, but he does not look patient right now.'),
  c('deadpan', 'Statistics are fun. But no number tells you what it feels like to step in against a hundred-mile-an-hour fastball when you have already struck out twice.'),
  c('deadpan', 'A coach once told me that you win the game in the sixth inning. It never made sense to me until I watched what happens when the starter runs out of gas.'),
  c('calm', 'The pitcher is starting to settle. Getting ahead, working the corners, and making the hitters swing at his pitch. That is exactly what you want.'),
  c('deadpan', 'Here is a stat for you. When the leadoff man reaches, the team scores more than half the time. That tells you why the first batter of the inning matters.'),
  c('deadpan', 'Nothing fires up a crowd like a hard slide into second and a clean break up of the double play.'),
  c('building', 'The tying run is on base and the dugout is leaning on the rail. This is the kind of moment players dream about when they are kids.'),
  c('deadpan', 'Defensive positioning is a quiet little science now. A step to the left, a step in, and suddenly that ground ball you thought was a hit is a routine out.'),
  c('calm', 'You get a sense of how this game has changed, but also how it has not. Three strikes, three outs, nine innings. Simple as that.'),
  c('deadpan', 'The first pitch is the most important pitch of the at-bat. Get ahead, and the hitter is on the defensive. Fall behind, and the pitcher has to come in with something hittable.'),
  c('deadpan', 'People forget how good the umpires are. Hundreds of calls a night, at speed, from forty feet away, and mostly they get it right.'),
  c('deadpan', 'Sometimes a pitcher will shake off the catcher just to change the rhythm. It does not mean anything, but it makes the hitter wait.'),
  c('building', 'We have a game on our hands, folks. Neither bullpen is giving an inch, and every pitch feels like it might be the one.'),
  c('deadpan', 'That is what makes the center fielder such an important part of the defense. He sees everything in front of him and calls everyone off.'),
  c('calm', 'The grounds crew will be out after the next half inning to give the dirt a little love, so enjoy this moment, because the infield is as perfect as it gets.'),
  c('deadpan', 'Over the course of a long season, the little things matter. A first-to-third here, a tag-up there, and suddenly you are a game ahead.'),
  c('deadpan', 'You see a left-handed pitcher with a good pickoff move, and suddenly stealing bases looks a lot less easy.'),
  c('deadpan', 'Interesting choice by the manager there. He brings in the lefty to face the lefty, and now we get to see whether the matchup works.'),
  c('building', 'The count goes to full, the runners will be moving, and the crowd rises. Here we go.'),
  c('deadpan', 'There is a reason hitters tap the plate and dig their toes in. It is a ritual, a way of saying: I am ready, bring it.'),
  c('calm', 'A nice, easy, one-two-three inning for the starter. That is exactly what you want to see from the man on the mound.'),
  c('deadpan', 'It is that time of year when every game matters, and every pitch is like a little playoff game. You can feel it in the way they play.'),
  c('deadpan', 'There is no replacement for experience. A veteran who has seen all of these situations knows exactly how to slow the game down.'),
  c('deadpan', 'Do you know the best sound in the world? The crack of the bat on a ball squared up, and the crowd rising before the ball even leaves the infield.'),
  c('building', 'He has to make a pitch here. He steps back, takes a breath, and everyone in this ballpark knows what is coming.'),
  c('deadpan', 'The best advice I ever got about hitting was to see the ball and hit the ball. Simple, and apparently very, very hard.'),
  c('calm', 'A good game of baseball is like a good book. You think you know how it will end, and then somebody turns the page and surprises you.'),
  c('deadpan', 'A pitcher who throws strikes is a pitcher who gets to go deep into the game. Walks kill you, and that is the lesson tonight.'),
  c('deadpan', 'People talk about the shift, the numbers, the spin rate. But in the end, the whole thing comes down to a person standing sixty feet six inches away, trying to throw something past another person.'),
  c('deadpan', 'Some nights you do not have your best stuff, and you have to find a way to get through six anyway. That is what makes a starter.'),
  c('building', 'And here is the stretch run. The {team} have won six of their last eight, and the crowd has started to believe.'),
  c('deadpan', 'If I could bottle that sound, the pop of the mitt on a ninety-eight mile an hour fastball, I would make a fortune.'),
  c('calm', 'It is a good, quick game tonight, with both pitchers working fast and the defense making all the plays.'),
  c('deadpan', 'It is the little things. A hustle double, a smart slide, a first baseman who stretches an extra inch. Those things win ballgames.'),
  c('deadpan', 'You always want to keep your head in the game on defense. One lapse, one throw to the wrong base, and the whole inning changes.'),
  c('building', 'The momentum is shifting, you can feel it. The dugout is loud, the crowd is loud, and the pitcher is rattled.'),
  c('deadpan', 'There is a lot of talk about analytics. But I think the best analytics is a veteran catcher who has seen this hitter a hundred times and knows exactly what he cannot hit.'),
  c('calm', 'Two good teams, a perfect night, and a ballgame that could go either way. Stick around, folks, because this is going to be fun.'),
  c('deadpan', 'Bunting for a hit is a lost art. The third baseman is back on his heels, and a good one down the line would be a real nuisance.'),
  c('deadpan', 'That is the thing about a pitching duel. Every mistake feels enormous, and every good pitch feels like a small victory.'),
  c('deadpan', 'There is nothing like the smell of freshly cut grass and the sound of the organ. If you cannot enjoy this, baseball may not be for you.'),
  c('building', 'And that is a huge strikeout, because the next hitter is the one you really do not want to face with a runner on third.'),
  c('deadpan', 'Every time the ball is put in play, something can happen. A wild throw, a bad hop, a dropped pop-up. That is why you watch.'),
  c('calm', 'A little ground ball back to the mound, and the pitcher throws him out by two steps. Easy work in the {ord}.'),
  c('deadpan', 'Players call it a grind, the one hundred and sixty-two game season. But when you are in it, one game at a time, it feels like a series of small battles.'),
  c('deadpan', 'There is a lot of baseball left. Do not leave early, because this game has a way of surprising you in the last two innings.'),
  c('deadpan', 'Watch the right fielder cheat toward the line there. He knows the batter pulls everything, and he knows the pitcher is going to pound the inside corner.'),
  c('building', 'This crowd is loud. This crowd is not going to let him settle down. And somebody has got to get an out.'),
  c('deadpan', 'Some hitters only want the fastball, and some can hit anything. The hard part is figuring out which kind you are facing.'),
  c('calm', 'The starter is finished for the night, with seven strong innings and a big hand from the crowd as he walks off the field.'),
  c('deadpan', 'I always say the best part about the ninth inning is that anything can happen, and in baseball, anything usually does.'),
  c('deadpan', 'You can win with pitching, you can win with power, you can win with speed. The best teams do all three on the same night.'),
  c('deadpan', 'There he goes, taking a big lead off first. He is going to give the pitcher a lot to think about, and the pitcher will probably pay for it.'),
  c('building', 'You could not draw it up any better. Bottom of the ninth, bases loaded, and the home team trailing by one.'),
  c('deadpan', 'It is a strange game. You can do everything right, and still walk off the field a loser. And you can do everything wrong, and the ball falls in.'),
  c('calm', 'The sun is almost gone, and the stadium lights are taking over. This is when the ballpark really comes alive.'),
  c('deadpan', 'The best hitters in the game tell you the same thing: they do not guess, they react. But it takes years to learn how to react.'),
  c('deadpan', 'If you want to understand this team, look at their baserunning. Aggressive, smart, and never afraid to take the extra base.'),
  c('deadpan', 'A pitcher with a great curveball is like a magician. You know where it is going, you just cannot do anything about it.'),
  c('building', 'And now the manager walks slowly to the mound. Everybody in the building knows what that means.'),
  c('deadpan', 'Baseball is the only sport where the defense has the ball, and the offense tries to hit it somewhere the defense is not. Think about that for a second.'),
  c('calm', 'Good evening, everybody, and welcome to another night of baseball here at Claudeball. We have got a great one for you tonight.'),
  c('calm', 'That will do it for us for now. Thanks for spending the evening with us, and we will see you at the ballpark.'),
];

/** General sentences for phonetic coverage (about 150; plain, natural, mostly baseball-flavoured so the voice stays on topic). */
export const SENTENCES: string[] = [
  'The pitcher shook off the sign and stared in at the plate.',
  'Please call Stella and ask her to bring these things from the store.',
  'A cold drink and a hot dog make a perfect afternoon.',
  'The batter stepped out of the box and tightened his gloves.',
  'We saw three tall trees beside the third base line.',
  'Nobody expected the runner to break for second on the first pitch.',
  'The shortstop dove to his left and came up throwing.',
  'Four fans in yellow shirts waved at the camera.',
  'She sells seashells by the seashore, but only on sunny days.',
  'The umpire brushed off the plate and set himself behind the catcher.',
  'Eight long weeks of practice finally paid off.',
  'He rounded third, looked at the coach, and kept running.',
  'The thick fog rolled in over the quiet harbor.',
  'A fast ball up and in sent the hitter back from the plate.',
  'Pass the salt, please, and tell them that dinner is ready.',
  'The crowd roared as the ball sailed over the center-field fence.',
  'Which of these jackets belongs to the boy by the door?',
  'Every pitch told a story, and the catcher knew how it would end.',
  'The old stadium creaked and groaned under thousands of happy feet.',
  'Just then, the lights flickered and the whole park went quiet.',
  'We should leave early to beat the traffic on the bridge.',
  'The coach clapped twice and sent the next batter to the plate.',
  'You can not catch them all, but you can always give it a try.',
  'A gentle breeze moved the flags above the right-field wall.',
  'Joe took a vacation to see the mountains and the lakes.',
  'He worked the count full and fouled off four straight pitches.',
  'The mayor threw out the first pitch with a big grin on her face.',
  'There was a long pause before the umpire gave the signal.',
  'It is not about how hard you hit the ball, but where you put it.',
  'The runner slid headfirst and dust flew in every direction.',
  'A quick snap throw caught the runner leaning the wrong way.',
  'Five black bats lay in a row beside the dugout steps.',
  'The kid in the front row held up his glove and hoped.',
  'Rain delayed the game for nearly an hour last Thursday.',
  'The home team batted last and needed just one more run.',
  'Take a deep breath, count to three, and try again.',
  'He was the kind of player who never missed a day.',
  'Birds circled the stadium as the sun dipped behind the stands.',
  'Many people think that the game is slow, but they have never watched closely.',
  'The pitching coach whispered something that made the rookie smile.',
  'Bring your own chair, because the seats fill up quickly.',
  'A tall glass of lemonade can cool anyone down.',
  'The first baseman stretched as far as he could and snagged the throw.',
  'Judging by the noise, the visitors had just taken the lead.',
  'Under the bright lights, the infield looked like a painting.',
  'The nervous young pitcher took a long look at the runner on first.',
  'What time does the game start, and where can we park?',
  'They paid a fair price for tickets near the visiting dugout.',
  'The left fielder made a running catch against the wall.',
  'Please keep your hands inside the railing at all times.',
  'He swung through the pitch and nearly lost his balance.',
  'Out in the bullpen, the closer began to loosen his arm.',
  'The young shortstop smiled and tossed the ball into the stands.',
  'It was a thrilling ending, and nobody wanted to go home.',
  'The wind carried the ball back toward the warning track.',
  'Beyond the fence, a freight train rumbled past the ballpark.',
  'She kept score in pencil, just in case of a change.',
  'The pitcher wiped his brow and went back to work.',
  'A solid single up the middle scored the runner from second.',
  'The rookie finally got his first big league hit.',
  'Seven more outs, and they would have won the pennant.',
  'Did you see how he moved his feet on that play?',
  'The scoreboard flashed a bright zero in the middle of the sixth.',
  'No one in the crowd could hear the umpire over the cheers.',
  'The captain pulled his cap low and walked to the mound.',
  'We watched the sunset from the top row of the upper deck.',
  'Throw strikes, trust your defense, and let them hit it.',
  'The pitcher uncorked a wild pitch, and the runner moved to third.',
  'Why would the manager leave a tired pitcher in there?',
  'The bat splintered on contact and the ball dribbled out to short.',
  'She cheered louder than anyone else in the whole section.',
  'Look for the exit sign above the walkway behind home plate.',
  'The right fielder made a perfect throw to the plate.',
  'By the end of the night, every seat was full.',
  'Their lineup had speed at the top and power in the middle.',
  'He threw a changeup in the dirt for ball three.',
  'The third baseman charged a slow roller and fired to first.',
  'Last year, this same team came back from five runs down.',
  'It was a quiet, steady kind of game, until the eighth.',
  'A pop fly drifted lazily toward the first base dugout.',
  'The umpire pointed to the fence, and the stadium exploded.',
  'There is a lot to like about the way he competes.',
  'In the next inning, the home team loaded the bases.',
  'The catcher snapped his glove shut and held the ball high.',
  'One more strike and the game would be over.',
  'The manager waved to the bullpen with two fingers.',
  'A hot summer breeze rolled across the field.',
  'He stole second base without a throw.',
  'That curveball dropped off the table.',
  'The fans stood and applauded for a full minute.',
  'Everyone remembers the first game they ever saw.',
  'The sinker darted in on his hands, and the bat broke in two.',
  'The announcer leaned toward the microphone and smiled.',
  'A long fly ball to the gap, and the runners are off.',
  'They shifted the infield toward the right side.',
  'He slapped the ball down the line for a double.',
  'The bullpen door swung open, and the crowd began to buzz.',
  'The batboy raced out to fetch the broken bat.',
  'You could hear a pin drop before the next pitch.',
  'The right-hander threw seven shutout innings on just eighty pitches.',
  'It was the kind of catch that gets played on the highlights all week.',
  'The team celebrated on the field with water and cheers.',
  'Both dugouts emptied, and then everyone went back to their places.',
  'Can you believe how far that ball went?',
  'He tipped his cap to the crowd and walked off the field.',
  'Anyone who has played this game knows how hard it can be.',
  'The pitcher pounded the glove and looked at the plate.',
  'She caught the foul ball with her bare hand and held it up.',
  'The visiting fans were quiet for most of the night.',
  'The ball bounced twice and rolled into the gap.',
  'A little patience goes a long way in this game.',
  'Once upon a time, this field was a farmer\'s pasture.',
  'Just before the pitch, a hush fell over the stands.',
  'We could use a hit right about now.',
  'The lead runner stopped at second, and the batter went to third on the throw.',
  'He battled all night, and he was rewarded in the end.',
  'Fresh popcorn and cold soda were the best part of the day.',
  'The scouts in the stands wrote furiously on their notepads.',
  'The ninth inning began with a pair of quick outs.',
  'A shallow fly ball dropped in front of the center fielder.',
  'His voice cracked as he thanked the crowd.',
  'The home plate umpire called time and wiped the plate again.',
  'A moment later, the whole ballpark was on its feet.',
  'Nothing beats a close game on a Friday night.',
  'The team bus was waiting outside the gate.',
  'Hold the runner, check the count, and play the shift.',
  'They looked tired, but they were not about to quit.',
  'A single run can change the course of an entire season.',
  'Wait a minute, did he really just do that?',
  'The knuckleball danced and darted, and the hitter had no chance.',
  'You never forget the sound of a crowd of forty thousand.',
  'The leadoff man worked a walk and took second on a wild pitch.',
  'The pitcher got the sign, came set, and threw to first.',
  'We were lucky to get such good seats for the game.',
  'The line drive hit the pitcher square on the foot.',
  'The slugger hit the ball so hard that it left a mark on the bat.',
  'Every batter in the lineup was hitting above two-fifty.',
  'He is hitting three-twelve with eighteen home runs.',
  'The starter went six strong with ten strikeouts and one walk.',
  'Did you know that a fastball takes less than half a second to reach the plate?',
  'It was a quarter past seven when the first pitch was thrown.',
  'The rookie wore number thirty-four and played in right field.',
  'A hundred and sixty-two games is a long time to play.',
  'The thermometer read ninety-one degrees in the shade.',
  'The visitors scored twice in the first, once in the third, and four times in the seventh.',
  'Fifty thousand fans filled the park to the very last row.',
  'The right fielder threw a strike to second, a full three hundred feet.',
  'He doubled in the second, singled in the fifth, and walked in the eighth.',
  'The ball traveled four hundred and twenty feet before it landed.',
  'For the first time in twelve years, they won the division.',
  'Between innings, the organ played an old familiar tune.',
  'The quick brown fox jumps over the lazy dog.',
  'How much wood would a woodchuck chuck if a woodchuck could chuck wood?',
  'Zero, one, two, three, four, five, six, seven, eight, nine.',
  'Sharp thinking and quick hands make a great infielder.',
  'Joyful voices echoed through the empty concourse.',
  'That was the best game of the season, by far.',
];
